use super::models::{EnforcementProfile, ProcessAction, ProcessCategory};

pub struct BrowserTargetSeed {
    pub target_key: &'static str,
    pub display_name: &'static str,
    pub keyword: &'static str,
    pub category_name: &'static str,
    pub confidence: f64,
}

/// macOS system / Apple bundled apps that should be demoted to the System
/// category by default so the inventory doesn't drown the user in noise.
pub const SYSTEM_APP_NAMES: &[&str] = &[
    "finder",
    "system settings",
    "system preferences",
    "activity monitor",
    "console",
    "disk utility",
    "keychain access",
    "screenshot",
    "screen sharing",
    "screencaptureui",
    "stocks",
    "weather",
    "maps",
    "freeform",
    "image capture",
    "preview",
    "photo booth",
    "automator",
    "shortcuts",
    "time machine",
    "voiceover utility",
    "audio midi setup",
    "directory utility",
    "migration assistant",
    "boot camp assistant",
    "airport utility",
    "bluetooth file exchange",
    "feedback assistant",
    "font book",
    "raycast",
    "spotlight",
    "siri",
    "loginwindow",
    "dock",
    "windowserver",
    "controlcenter",
    "notificationcenter",
    "talagent",
    "coreservicesuiagent",
    "cfprefsd",
    "powerd",
    "configd",
    "syslogd",
    "wifiagent",
    "mdworker",
    "mds",
    "spotlightnetworkhelper",
    "bird",
    "cloudd",
    "rapportd",
    "useventagent",
    "trustd",
    "appleidauthagent",
    "secd",
    "tccd",
];

/// Path prefixes that mark a discovered bundle as a built-in / vendor system
/// app on macOS. Anything under these gets the System category guess.
pub const MACOS_SYSTEM_PATH_PREFIXES: &[&str] = &[
    "/System/Applications/",
    "/System/Library/",
    "/Library/Apple/",
    "/Library/Frameworks/",
    "/Library/PrivilegedHelperTools/",
    "/Applications/Utilities/",
    "/usr/libexec/",
    "/usr/sbin/",
    "/usr/bin/",
];

/// Path fragments that mark an item discovered inside another .app bundle as
/// an internal helper, plugin, XPC service or framework component — those
/// should never surface to the user as a top-level app.
pub const MACOS_EMBEDDED_HELPER_FRAGMENTS: &[&str] = &[
    ".app/Contents/Frameworks/",
    ".app/Contents/Helpers/",
    ".app/Contents/PlugIns/",
    ".app/Contents/XPCServices/",
    ".app/Contents/Resources/",
    ".app/Contents/Library/",
    ".appex/",
    ".xpc/",
];

pub fn is_macos_embedded_helper_path(path: &str) -> bool {
    MACOS_EMBEDDED_HELPER_FRAGMENTS
        .iter()
        .any(|fragment| path.contains(fragment))
}

pub fn built_in_categories() -> Vec<ProcessCategory> {
    vec![
        ProcessCategory {
            name: "System".to_string(),
            process_names: SYSTEM_APP_NAMES
                .iter()
                .map(|name| (*name).to_string())
                .collect(),
            default_action: ProcessAction::AlwaysAllow,
        },
        ProcessCategory {
            name: "Games".to_string(),
            process_names: vec![
                "steam".to_string(),
                "steam_osx".to_string(),
                "epicgameslauncher".to_string(),
                "riot client".to_string(),
                "battle.net".to_string(),
            ],
            default_action: ProcessAction::AlwaysBlock,
        },
        ProcessCategory {
            name: "Social Media".to_string(),
            process_names: vec![
                "discord".to_string(),
                "telegram".to_string(),
                "whatsapp".to_string(),
                "signal".to_string(),
                "wechat".to_string(),
                "wechatappex".to_string(),
            ],
            default_action: ProcessAction::BlockDuringWork,
        },
        ProcessCategory {
            name: "Entertainment".to_string(),
            process_names: vec![
                "spotify".to_string(),
                "vlc".to_string(),
                "iina".to_string(),
                "netflix".to_string(),
                "bilibili".to_string(),
            ],
            default_action: ProcessAction::AllowDuringBreak,
        },
        ProcessCategory {
            name: "Communication".to_string(),
            process_names: vec![
                "gmail".to_string(),
                "outlook".to_string(),
                "slack".to_string(),
                "teams".to_string(),
            ],
            default_action: ProcessAction::AlwaysAllow,
        },
        ProcessCategory {
            name: "Browsers".to_string(),
            process_names: vec![
                "google chrome".to_string(),
                "firefox".to_string(),
                "safari".to_string(),
                "microsoft edge".to_string(),
                "arc".to_string(),
                "brave browser".to_string(),
            ],
            default_action: ProcessAction::AlwaysAllow,
        },
        ProcessCategory {
            name: "Development".to_string(),
            process_names: vec![
                "code".to_string(),
                "visual studio code".to_string(),
                "vscode".to_string(),
                "codex".to_string(),
                "codex computer use".to_string(),
                "claude".to_string(),
                "claude code".to_string(),
                "claude code url handler".to_string(),
                "cursor".to_string(),
                "xcode".to_string(),
                "android studio".to_string(),
                "intellij idea".to_string(),
                "pycharm".to_string(),
                "webstorm".to_string(),
                "rubymine".to_string(),
                "phpstorm".to_string(),
                "rider".to_string(),
                "clion".to_string(),
                "datagrip".to_string(),
                "goland".to_string(),
                "fleet".to_string(),
                "zed".to_string(),
                "sublime text".to_string(),
                "neovide".to_string(),
                "iterm".to_string(),
                "terminal".to_string(),
                "warp".to_string(),
                "ghostty".to_string(),
                "alacritty".to_string(),
                "kitty".to_string(),
                "hyper".to_string(),
                "wezterm".to_string(),
                "docker desktop".to_string(),
                "github desktop".to_string(),
                "sourcetree".to_string(),
                "tower".to_string(),
                "postman".to_string(),
                "insomnia".to_string(),
                "tableplus".to_string(),
                "dbeaver".to_string(),
                "proxyman".to_string(),
                "charles".to_string(),
            ],
            default_action: ProcessAction::AlwaysAllow,
        },
        ProcessCategory {
            name: "Productivity".to_string(),
            process_names: vec![
                "notion".to_string(),
                "obsidian".to_string(),
                "logseq".to_string(),
                "bear".to_string(),
                "craft".to_string(),
                "evernote".to_string(),
                "onenote".to_string(),
                "things".to_string(),
                "todoist".to_string(),
                "ticktick".to_string(),
                "omnifocus".to_string(),
                "trello".to_string(),
                "asana".to_string(),
                "linear".to_string(),
                "jira".to_string(),
                "notes".to_string(),
                "reminders".to_string(),
                "raycast".to_string(),
                "alfred".to_string(),
                "rectangle".to_string(),
                "magnet".to_string(),
                "1password".to_string(),
                "bitwarden".to_string(),
                "calendar".to_string(),
                "fantastical".to_string(),
                "amie".to_string(),
                "vimcal".to_string(),
                "cron".to_string(),
                "sunsama".to_string(),
                "freeform".to_string(),
            ],
            default_action: ProcessAction::AlwaysAllow,
        },
        ProcessCategory {
            name: "Creative".to_string(),
            process_names: vec![
                "photoshop".to_string(),
                "illustrator".to_string(),
                "indesign".to_string(),
                "premiere pro".to_string(),
                "after effects".to_string(),
                "lightroom".to_string(),
                "figma".to_string(),
                "sketch".to_string(),
                "framer".to_string(),
                "blender".to_string(),
                "logic pro".to_string(),
                "garageband".to_string(),
                "ableton live".to_string(),
                "fl studio".to_string(),
                "audacity".to_string(),
                "musescore".to_string(),
                "musescore 4".to_string(),
                "muse hub".to_string(),
                "mainstage".to_string(),
                "sibelius".to_string(),
                "imslp".to_string(),
                "blackmagic proxy generator lite".to_string(),
                "blackmagic raw player".to_string(),
                "blackmagic raw speed test".to_string(),
                "blackmagic raw".to_string(),
                "davinci resolve".to_string(),
                "final cut pro".to_string(),
                "imovie".to_string(),
                "obs studio".to_string(),
                "procreate".to_string(),
                "affinity designer".to_string(),
                "affinity photo".to_string(),
                "affinity publisher".to_string(),
                "pixelmator pro".to_string(),
                "capture one".to_string(),
                "krita".to_string(),
            ],
            default_action: ProcessAction::AlwaysAllow,
        },
        ProcessCategory {
            name: "Utilities".to_string(),
            process_names: vec![
                "the unarchiver".to_string(),
                "keka".to_string(),
                "appcleaner".to_string(),
                "cleanmymac x".to_string(),
                "macupdater".to_string(),
                "transmission".to_string(),
                "parallels desktop".to_string(),
                "vmware fusion".to_string(),
                "virtualbox".to_string(),
                "utm".to_string(),
                "homebrew".to_string(),
                "carbon copy cloner".to_string(),
                "stats".to_string(),
                "istat menus".to_string(),
                "shottr".to_string(),
                "cleanshot x".to_string(),
            ],
            default_action: ProcessAction::AlwaysAllow,
        },
    ]
}

pub fn built_in_profile_names() -> Vec<EnforcementProfile> {
    let now = 0;
    vec![
        EnforcementProfile {
            name: "rest".to_string(),
            parent_name: None,
            builtin: true,
            created_at: now,
            updated_at: now,
        },
        EnforcementProfile {
            name: "work".to_string(),
            parent_name: Some("rest".to_string()),
            builtin: true,
            created_at: now,
            updated_at: now,
        },
        EnforcementProfile {
            name: "deep_work".to_string(),
            parent_name: Some("work".to_string()),
            builtin: true,
            created_at: now,
            updated_at: now,
        },
        EnforcementProfile {
            name: "emergency".to_string(),
            parent_name: None,
            builtin: true,
            created_at: now,
            updated_at: now,
        },
    ]
}

pub const EMERGENCY_PROFILE_NAME: &str = "emergency";

pub const EMERGENCY_BLOCKED_CATEGORIES: &[&str] = &["Games", "Entertainment"];

pub fn built_in_browser_targets() -> Vec<BrowserTargetSeed> {
    vec![
        BrowserTargetSeed {
            target_key: "youtube",
            display_name: "YouTube",
            keyword: "youtube",
            category_name: "Entertainment",
            confidence: 0.98,
        },
        BrowserTargetSeed {
            target_key: "twitter",
            display_name: "Twitter/X",
            keyword: "twitter",
            category_name: "Social Media",
            confidence: 0.95,
        },
        BrowserTargetSeed {
            target_key: "x",
            display_name: "Twitter/X",
            keyword: " x ",
            category_name: "Social Media",
            confidence: 0.7,
        },
        BrowserTargetSeed {
            target_key: "reddit",
            display_name: "Reddit",
            keyword: "reddit",
            category_name: "Social Media",
            confidence: 0.95,
        },
        BrowserTargetSeed {
            target_key: "netflix",
            display_name: "Netflix",
            keyword: "netflix",
            category_name: "Entertainment",
            confidence: 0.98,
        },
        BrowserTargetSeed {
            target_key: "instagram",
            display_name: "Instagram",
            keyword: "instagram",
            category_name: "Social Media",
            confidence: 0.95,
        },
        BrowserTargetSeed {
            target_key: "facebook",
            display_name: "Facebook",
            keyword: "facebook",
            category_name: "Social Media",
            confidence: 0.95,
        },
        BrowserTargetSeed {
            target_key: "tiktok",
            display_name: "TikTok",
            keyword: "tiktok",
            category_name: "Entertainment",
            confidence: 0.95,
        },
        BrowserTargetSeed {
            target_key: "bilibili",
            display_name: "Bilibili",
            keyword: "bilibili",
            category_name: "Entertainment",
            confidence: 0.95,
        },
        BrowserTargetSeed {
            target_key: "bilibili-cn",
            display_name: "Bilibili",
            keyword: "哔哩哔哩",
            category_name: "Entertainment",
            confidence: 0.95,
        },
        BrowserTargetSeed {
            target_key: "gmail",
            display_name: "Gmail",
            keyword: "gmail",
            category_name: "Communication",
            confidence: 0.92,
        },
    ]
}
